title: Ian Murray
author:
  name: Ian Murray
  email: consulting@ianmurray.me
description: >-
  I'm a Software Engineer who develops with Ruby and Node. I focus primarily on
  API development, but also develop entire systems with Ruby on Rails, and
  mobile apps using Flutter and Firebase.
baseurl: ""
url: "https://ianmurray.me"

plugins:
  - jekyll-feed
  - jekyll-tailwind
  - jekyll-paginate-v2
  - jekyll-seo-tag

tailwind:
  input: assets/css/app.css
  minify: true

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_reverse: true

social_links:
  github: "https://github.com/ianmurrays"
  linkedin: "https://linkedin.com/in/ianmurrays"
  instagram: "https://instagram.com/ianmurrays"

header_pages:
  - blog.markdown
  - now.markdown
  - contact.markdown
